version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4
    steps:
      - checkout
      - restore_cache:
          key: {{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "build_tools/circle/install.sh" }}
      - run:
          command: |
            bash build_tools/circle/install.sh
      - save_cache:
          key: {{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "build_tools/circle/install.sh" }}
          paths:
            - /opt/conda/pkgs
