version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "build_tools/circle/install.sh" }}
      - run:
          name: Install dependencies
          command: |
            bash build_tools/circle/install.sh
            rm /opt/conda/pkgs/*.tar.bz2
            rm /opt/conda/pkgs/urls.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "build_tools/circle/install.sh" }}
          paths:
            - /opt/conda/pkgs
      - run:
          name: Run build
          command: |
            bash build_tools/circle/execute.sh
